HotelBookingApp/Controllers/RoomCategoryController.cs
using HotelBookingApp.Models;
using HotelBookingApp.Repository;
using Microsoft.AspNetCore.Mvc;

namespace HotelBookingApp.Controllers
{
    public class RoomCategoryController : Controller
    {
        private readonly IRoomCategoryRepository _repo;

        public RoomCategoryController(IRoomCategoryRepository repo)
        {
            _repo = repo;
        }

        public async Task<IActionResult> GetAllRoomCategory()
        {

            var catlist = await _repo.GetAllRoomCategories();
            return View(catlist);

        }

    }
}

HotelBookingApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<ApplicationUser> _signInManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HotelBookingApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HotelBookingApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HotelBookingApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Booking" asp-action="GetAllBookings">Bookings</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Room" asp-action="GetAllRooms">Rooms</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RoomCategory" asp-action="GetAllRoomCategory">Category</a>
                        </li>
                          <li class="nav-item" >
                        <a style="padding-right:10%" class="nav-link collapsed" asp-controller="Account" asp-action="Login">
                            <i  class="bi bi-box-arrow-in-right"></i>
                            <span>Login</span>
                        </a>
                    <li class="nav-item" >
                        <a style="padding-right:10%" class="nav-link collapsed" asp-controller="Account" asp-action="Register">
                            <i  class="bi bi-card-list"></i>
                            <span>Register</span>
                        </a>
                    </li>

                            @if (_signInManager.IsSignedIn(User))
                            {
                        <li class="nav-item dropdown pe-3">


                            <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
                                <img src="assets/img/profile-img.jpg" alt="Profile" class="rounded-circle">
                                <span class="d-none d-md-block dropdown-toggle ps-2">@User.Identity.Name</span> <!--Edit Name of User-->
                            </a>
                            <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">


                               @* <li class="dropdown-header">
                                    <h6>Profile</h6>
                                    <span>Web Designer</span>
                                </li>*@
                                <li>
                                    <hr class="dropdown-divider">
                                </li>

                                <li>
                                    <a class="dropdown-item d-flex align-items-center" href="users-profile.html">
                                        <i class="bi bi-person"></i>
                                        <span>My Profile</span>
                                    </a>
                                </li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>

                                <li>
                                    <a class="dropdown-item d-flex align-items-center" asp-controller="Account" asp-action="ChangePassword">
                                        <i class="bi bi-gear"></i>
                                        <span>Change Password</span>
                                    </a>
                                </li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>

                                <li>
                                    <a class="dropdown-item d-flex align-items-center" asp-controller="Account" asp-action="Logout">
                                        <i class="bi bi-question-circle"></i>
                                        <span>Sign Out</span>
                                    </a>
                                </li>
                               
                                   


                            </ul><!-- End Profile Dropdown Items -->
                        </li>
                            }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - HotelBookingApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>